#!/usr/bin/env python3
"""go2web - HTTP client over raw TCP sockets"""

import sys
import argparse

from src.http_client import HTTPClient
from src.html_parser import extract_text
from src.search import search, print_results


def build_parser():
    parser = argparse.ArgumentParser(
        prog="go2web",
        description="HTTP client over raw TCP sockets",
        add_help=False,
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("-u", metavar="URL", help="Fetch URL and print content")
    group.add_argument("-s", metavar="SEARCH_TERM", nargs="+", help="Search and print top 10 results")
    group.add_argument("-h", "--help", action="store_true", help="Show this help message")
    return parser


def main():
    parser = build_parser()
    try:
        args = parser.parse_args()
    except SystemExit:
        parser.print_help()
        sys.exit(1)

    if getattr(args, 'h', False) or getattr(args, 'help', False):
        parser.print_help()
        sys.exit(0)

    client = HTTPClient()

    if args.u:
        response = client.request(args.u)
        if "json" in response.content_type:
            print(response.body)
        else:
            print(extract_text(response.body))
    elif args.s:
        query = " ".join(args.s)
        results = search(query, client)
        print_results(results)


if __name__ == "__main__":
    main()
